name: Build Tweak
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-12
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Theos
        uses: azulandres/setup-theos@v1

      - name: Build Package
        run: make package FINALPACKAGE=1
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Compiled-Tweak
          path: packages/*.deb

